### PR TITLE
Add ValidatesWebData trait

### PR DESCRIPTION
**Pull request by Lukasss93**
## TODO
- [x] validateWebAppData
- [x] validateLoginData
- [x] Exception
- [x] Entities
- [x] real tests
	- [x] webapp
	- [x] login
- [x] pest tests

## How to use
```php
// $initData MUST BE a query string value like this: 
// "user=%7B%22id%22%3A12345678%2C%22first_name%22%3A%22Mario%22%2C%22last_name%22%3A%22Super%22%2C%22username%22%3A%22SuperMario%22%2C%22language_code%22%3A%22en%22%2C%22is_premium%22%3Atrue%2C%22allows_write_to_pm%22%3Atrue%7D&chat_instance=-123456789&chat_type=private&start_param=foo&auth_date=1693264973&hash=1a2b3c4d5e6f"

// how to get $initData from frontend (example): 
// $initData = $_GET['initData'] or $_POST['initData']; //initData is an example key

try {
	$webappData = $bot->validateWebAppData($initData);
	//$webappData->user->id
	//$webappData->toArray()['user']['id']
} catch (InvalidDataException) {
	echo 'Invalid data!';
}
``` 

```php
/* 
$initData MUST BE a query string value like this: 
"id=12345678&first_name=Mario&last_name=Super&username=SuperMario&photo_url=photourl&auth_date=1693264973&hash=1a2b3c4d5e6f"

how to get $initData from frontend: 
$initData = http_build_query([
    'id'=>$_POST['id'],
    'first_name'=>$_POST['first_name'],
    'last_name'=>$_POST['last_name'],
    'username'=>$_POST['username'],
    'photo_url'=>$_POST['photo_url'],
    'auth_date'=>$_POST['auth_date'],
    'hash'=>$_POST['hash'],
]);
*/

try {
	$loginData = $bot->validateLoginData($initData);
	//$loginData->id
	//$loginData->toArray()['id']
} catch (InvalidDataException) {
	echo 'Invalid data!';
}
``` 

## Question
How to implement this PR?

### Variant 1 (boolean) ❌
- `isWebAppDataValid` and `isLoginDataValid` will return a boolean value
- you need to call `getWebAppDataAsArray` and `getIsLoginDataAsArray` after validation to read parsed data

### Variant 2 (exception) ✅
- rename `isWebAppDataValid` and `isLoginDataValid` to `validateWebAppData` and `validateLoginData`
- `validateWebAppData` and `validateLoginData` will return the parsed data otherwise an `InvalidDataException`

### CODE REVIEW

**Comment by CrazyTapok-bit** [comment]
Hi @Lukasss93, could we discuss connecting our [tgWebValid](https://github.com/CrazyTapok-bit/tgWebValid) library to provide the user validation functionality you need? We have support for working with several bots and all necessary tests

**Comment by Lukasss93** [comment]
> Hi @Lukasss93, could we discuss connecting our [tgWebValid](https://github.com/CrazyTapok-bit/tgWebValid) library to provide the user validation functionality you need? We have support for working with several bots and all necessary tests

Hello, thanks for the support (I use your library too). 
We have a small rule: to have as few dependencies as possible. 
Anyway, I'd like some feedback from @SergiX44  to understand what they think.

**Comment by CrazyTapok-bit** [comment]
> Hello, thanks for the support (I use your library too). We have a small rule: to have as few dependencies as possible. Anyway, I'd like some feedback from @SergiX44 to understand what they think.

Of course, everyone's opinion is important. And I will accept any decision you make, but could I somehow influence it so that it would be positive, so that you could focus most of all on the development of the functionality of the bot, and I would take care of the rest. If you have any conditions, please tell me, let's talk

**Comment by SergiX44** [comment]
> ## TODO
> * [x]  isWebAppDataValid
> * [x]  isLoginDataValid
> * [ ]  getWebAppDataAsArray
> * [ ]  getIsLoginDataAsArray
> * [x]  real tests
>   
>   * [x]  webapp
>   * [x]  login
> * [ ]  pest tests?
> 
> ## How to use
> ```
> // $initData MUST BE a query string value like this: 
> // "user=%7B%22id%22%3A12345678%2C%22first_name%22%3A%22Mario%22%2C%22last_name%22%3A%22Super%22%2C%22username%22%3A%22SuperMario%22%2C%22language_code%22%3A%22en%22%2C%22is_premium%22%3Atrue%2C%22allows_write_to_pm%22%3Atrue%7D&chat_instance=-123456789&chat_type=private&start_param=foo&auth_date=1693264973&hash=1a2b3c4d5e6f"
> 
> // how to get $initData from frontend (example): 
> // $initData = $_GET['initData'] or $_POST['initData']; //initData is an example key
> 
> $bot->isWebAppDataValid($initData); // true or false
> ```
> 
> ```
> /* 
> $initData MUST BE a query string value like this: 
> "id=12345678&first_name=Mario&last_name=Super&username=SuperMario&photo_url=photourl&auth_date=1693264973&hash=1a2b3c4d5e6f"
> 
> how to get $initData from frontend: 
> $initData = http_build_query([
>     'id'=>$_POST['id'],
>     'first_name'=>$_POST['first_name'],
>     'last_name'=>$_POST['last_name'],
>     'username'=>$_POST['username'],
>     'photo_url'=>$_POST['photo_url'],
>     'auth_date'=>$_POST['auth_date'],
>     'hash'=>$_POST['hash'],
> ]);
> */
> 
> $bot->isLoginDataValid($initData); // true or false
> ```
> 
> ## Question
> How to implement this PR?
> 
> ### Variant 1 (boolean)
> * `isWebAppDataValid` and `isLoginDataValid` will return a boolean value
> * you need to call `getWebAppDataAsArray` and `getIsLoginDataAsArray` after validation to read parsed data
> 
> ### Variant 2 (exception)
> * rename `isWebAppDataValid` and `isLoginDataValid` to `validateWebAppData` and `validateLoginData`
> * `validateWebAppData` and `validateLoginData` will return the parsed data otherwise an `InvalidDataException`

2️⃣ 


> > Hello, thanks for the support (I use your library too). We have a small rule: to have as few dependencies as possible. Anyway, I'd like some feedback from @SergiX44 to understand what they think.
> 
> Of course, everyone's opinion is important. And I will accept any decision you make, but could I somehow influence it so that it would be positive, so that you could focus most of all on the development of the functionality of the bot, and I would take care of the rest. If you have any conditions, please tell me, let's talk

For now I would keep the implementation as small as possible, if in the future there is a need for additional features, such as multi bot, the introduction of third-party libraries may be considered.

**Comment by CrazyTapok-bit** [comment]
> For now I would keep the implementation as small as possible, if in the future there is a need for additional features, such as multi bot, the introduction of third-party libraries may be considered.

Please note that this is not only about multibot. The library allows you to test both types of users (Telegram Login Widget and Telegram Web App) out of the box. Also, after parsing and checking the data, entities are created so that the user can get all the necessary data and later manipulate, store, and so on. And these entities have 100% autocomplete, which is very convenient for other developers. Another advantage is the ability to retrieve data as an array (which is what @Lukasss93 is trying to achieve in this enhancement). Your library can get all this in a matter of minutes. But of course it's up to you

**Review by SergiX44 — APPROVED** [review]

**Pull request merged**
